import React from 'react';

export type Language = 'zh-CN' | 'en-US';

type Dictionary = Record<string, string>;

const STORAGE_KEY = 'payDemo.language';

const dictionaries: Record<Language, Dictionary> = {
  'zh-CN': {
    'language.title': 'Language',
    'language.zh': '中文',
    'language.en': 'EN',
    'common.prevStep': '上一步',
    'common.pciApiPrerequisite': '集成前提：已具备 PCI 资质方可使用 API 模式集成',
    'mode.STANDARD': '标准收单',
    'mode.SUBSCRIPTION': '订阅代扣',
    'mode.PAYMENT_LINK': '链接支付',
    'sidebar.subscriptionConfig': 'Subscription Config',
    'sidebar.paymentConfiguration': 'Payment Configuration',
    'sidebar.businessMode': '业务模式',
    'sidebar.integrationMode': '集成方式',
    'sidebar.paymentMethod': '支付方式',
    'sidebar.paymentConfig': '支付配置',
    'sidebar.resetAllSteps': '↻ 重置所有步骤',
    'sidebar.chooseMode': '请从顶部选择业务模式',
    'sidebar.allCashier': '全部收银台',
    'sidebar.cashierAll': '全量收银台',
    'sidebar.cashierSpecific': '指定支付方式',
    'sidebar.managedByPayerMax': 'MANAGED BY PAYERMAX',
    'sidebar.fullCashierHint1': '• 全量收银台模式下，无需指定方式',
    'sidebar.fullCashierHint2': '• 终端用户可在 PayerMax 页面自主选择',
    'sidebar.standardTip': '切换不同的集成模式，右侧代码报文将同步更新。',
    'sidebar.linkTip': '链接支付支持多种分发场景，无论是后台手动还是 API 自动。',
    'sidebar.apmTipLine1': 'APM 订阅激活传 ONE_TOUCH，并默认 targetOrg: KAKAOPAY。',
    'sidebar.apmTipLine2': '当前演示已固定使用 KR / KRW。',
    'subMode.payermax.name': 'PayerMax托管（周期性订阅）',
    'subMode.payermax.desc': 'PayerMax管理订阅计划与扣款周期',
    'subMode.merchant.name': '商户自管（周期性订阅）',
    'subMode.merchant.desc': '商户自主管理订阅计划与扣款时机',
    'subMode.nonperiodic.name': '非周期性订阅代扣',
    'subMode.nonperiodic.desc': '商户按业务需求灵活发起扣款',
    'integration.cashier': '收银台绑定 / 激活',
    'integration.api': 'API 绑定 / 激活',
    'integration.component': '前置组件绑定 / 激活',
    'paymentIntegration.cashier.label': '收银台模式',
    'paymentIntegration.cashier.desc': '重定向至 PayerMax 托管收银台页面完成支付',
    'paymentIntegration.api.label': 'API 模式',
    'paymentIntegration.api.desc': '完全自主控制支付 UI',
    'paymentIntegration.component.label': '前置组件模式',
    'paymentIntegration.component.desc': '在商户页面内嵌入 PayerMax 提供的极简支付组件',
    'linkMode.dashboard.label': '商户后台创建链接',
    'linkMode.dashboard.desc': '登录 PayerMax 商户平台（MMC）录入订单并生成链接/二维码，无需开发创建接口。',
    'linkMode.api.label': 'API 创建链接',
    'linkMode.api.desc': '通过 createPaybylink 动态生成支付链接，适合自动化和批量分发。',
    'code.note.standard': '前端第一步收集商品、用户和支付选择，用于后续请求PayerMax接口',
    'code.note.subscription': '前端第一步收集用户选择的业务参数，用于后续请求PayerMax接口',
    'code.note.link': '前端第一步收集支付链接商品参数，用户或许创建链接使用',
    'code.next.standard.order': 'orderAndPay 创建支付订单',
    'code.next.standard.component': 'applySession 获取 sessionKey，或 orderAndPay 下单',
    'code.next.link': 'createPaybylink 返回 linkUrl 与 qrCodeUrl',
    'code.next.subscription.payermax': '创建 PayerMax 管理订阅计划 subscriptionCreate',
    'code.next.subscription.mandate': '首次绑定支付方式 orderAndPay，获取 paymentTokenID 供后续扣款',
    'code.empty': '完成本步骤操作后，将展示真实请求与响应。',
    'result.orderReturned': 'orderAndPay 已返回',
    'result.api': '接口',
    'result.paymentMethod': '支付方式',
    'result.status': '返回状态',
    'result.check': '查看支付结果',
    'result.returnReceived': '落地页已返回',
    'result.orderNo': '订单号',
    'standard.checkout.3dsComplete': '完成3DS验证，返回下单结果',
    'standard.checkout.paymentComplete': '完成页面支付，查看支付结果',
    'standard.checkout.requestingOrder': '正在请求 orderAndPay',
    'standard.checkout.orderDisplay': '下单展示',
    'standard.checkout.cashierPayment': '全量收银台',
    'standard.checkout.requestSent': '',
    'standard.checkout.processingPayment': '正在处理支付请求，请稍候。',
    'standard.checkout.cashierLoading': 'PayerMax 会话正在初始化，将为用户提供多种支付方式选择。',
    'standard.checkout.waitingResult': '等待下单结果',
    'standard.component.paymentComplete': '完成页面支付，查看支付结果',
    'standard.component.readyOrder': '准备调用 orderAndPay',
    'standard.component.useToken': '将第二步获取到的 paymentToken 和 sessionKey 用于前端 JS 直连 PayerMax orderAndPay 完成下单支付。',
    'standard.component.tokenReadyHint': '获取到 Token 后用于后续下单。',
    'standard.component.callOrder': '调用 orderAndPay',
    'standard.toast.needSelfCashierSelection': '请先在右侧仿真手机点击 Buy Now，并在自建收银台内选择支付方式。',
    'standard.toast.needComponentAuth': '请先在右侧仿真手机内选择支付方式并完成组件授权，获取 paymentToken 后再执行下一步。',
    'standard.toast.needComponentToken': '请先回到右侧仿真手机自建收银台获取 paymentToken，再执行 orderAndPay。',
    'standard.toast.needPaymentMethod': '请先在右侧仿真手机内选择支付方式。',
    'standard.error.sessionFailed': '会话获取失败',
    'standard.error.networkFailed': '网络请求失败，请检查服务状态',
    'standard.error.paymentFailed': '支付失败：{reason}',
    'standard.error.orderFailed': '下单失败：{reason}',
    'standard.error.browserDirectFailed': '浏览器直连 PayerMax 请求失败',
    'standard.error.browserDirectFailedFull': '浏览器直连 PayerMax 请求失败，请检查网络、CORS 或签名配置',
    'standard.error.missingOrderQuery': '缺少 orderQuery 查询参数',
    'subscription.config.planTitle': '订阅套餐',
    'subscription.config.planDesc': 'PayerMax 托管模式会把套餐规则写入 subscriptionCreate，由 PayerMax 管理后续周期扣款。',
    'subscription.config.merchantTitle': '商户自管规则',
    'subscription.config.merchantDesc': 'PayerMax 只完成首次绑定并返回 paymentTokenID；订阅周期、优惠期和后续扣款金额由商户系统自行管理。',
    'subscription.config.nonperiodicTitle': '非周期代扣规则',
    'subscription.config.nonperiodicDesc': '首次绑定成功后保存 paymentTokenID；后续由商户按业务触发扣款，不存在固定订阅周期。',
    'subscription.config.parameters': '参数配置',
    'subscription.config.apmFixed': 'APM 订阅演示固定使用 KR / KRW：后续扣款 1000，优惠期 100，试用激活 0。',
    'subscription.config.totalPeriods': '总期数',
    'subscription.config.periodCount': '扣款频率',
    'subscription.config.periodUnit': '周期单位',
    'subscription.config.unit.D': '日',
    'subscription.config.unit.W': '周',
    'subscription.config.unit.M': '月',
    'subscription.config.unit.Y': '年',
    'subscription.config.amount': '每期金额',
    'subscription.config.currency': '币种',
    'subscription.config.trialDays': '试用天数',
    'subscription.config.discountPeriods': '优惠期数',
    'subscription.config.discountAmount': '优惠期金额',
    'subscription.config.laterPlanAmount': '后续计划扣款金额',
    'subscription.config.firstAndLaterAmount': '首次及后续扣款金额',
    'subscription.config.laterOnDemandAmount': '后续按需扣款金额',
    'subscription.config.subject': '订单标题',
    'subscription.config.userId': '用户 ID',
    'subscription.config.firstBindType': '首次绑定类型',
    'subscription.config.zeroBind': '首次 0 元绑定',
    'subscription.config.paidBind': '首次 >0 元绑定',
    'subscription.config.zeroBindDesc': '只完成授权并获取 token',
    'subscription.config.paidBindDesc': '绑定同时完成首笔支付',
    'subscription.config.firstAmount': '首次金额',
    'subscription.config.firstBindAmount': '首次绑定金额',
    'subscription.config.laterDebitAmount': '后续扣款金额',
    'subscription.config.mitType': 'MIT 类型',
    'subscription.config.trialScenario': '试用场景',
    'subscription.config.firstPayScenario': '首付场景',
    'subscription.config.zeroMerchantDesc': '用户先完成授权并生成 paymentTokenID，商户在试用期结束后按订阅规则发起扣款。',
    'subscription.config.zeroNonperiodicDesc': '用户先完成扣款授权并生成 paymentTokenID，后续由商户按业务需要灵活发起扣款。',
    'subscription.config.paidMerchantDesc': '适用于前 N 期优惠或正常订阅，首次绑定时同步完成首笔支付并保存 token。',
    'subscription.config.paidNonperiodicDesc': '适用于首次即收取费用的授权，绑定成功后商户保管 token 用于后续按需扣款。',
    'subscription.config.merchantPreviewTitle': '商户自管订阅',
    'subscription.config.nonperiodicPreviewTitle': '非周期性代扣',
    'subscription.config.previewHint': '选择首次绑定金额类型，后续扣款计划由商户自行管理。',
    'subscription.config.nextOrderHint': '下一步将调用 orderAndPay 完成首次下单绑定。',
    'subscription.config.firstOrderBind': '首次下单绑定',
    'subscription.type.standard.label': '普通订阅',
    'subscription.type.standard.desc': '绑定金额 > 0',
    'subscription.type.trial.label': 'N天试用',
    'subscription.type.trial.desc': '绑定金额 = 0',
    'subscription.type.discount.label': '前N期优惠',
    'subscription.type.discount.desc': '绑定金额 > 0',
    'subscription.type.trial_discount.label': 'N天试用 + 前N期优惠',
    'subscription.type.trial_discount.desc': '组合优惠',
    'subscription.create.title': '创建订阅计划',
    'subscription.create.creating': '正在创建订阅计划...',
    'subscription.create.calling': '正在调用 PayerMax subscriptionCreate',
    'subscription.create.success': '创建成功 — 返回订阅计划号',
    'subscription.create.inactive': '当前状态：INACTIVE，下一步需要用户完成首次授权/支付来激活。',
    'subscription.create.preparingSession': '正在预取前置组件 Session...',
    'subscription.create.sessionReady': '组件 Session 已准备',
    'subscription.create.sessionReadyHint': '进入自建收银台后将按用户选择动态挂载组件。',
    'subscription.create.requestingOrder': '正在请求 orderAndPay',
    'subscription.create.enterCashier': '进入自建收银台',
    'subscription.create.activate': '进入激活订阅',
    'subscription.create.retry': '重新创建',
    'subscription.create.errorCreate': '创建订阅失败',
    'subscription.create.errorSession': '预取前置组件 Session 失败',
    'subscription.create.errorActivate': '激活订阅失败',
    'subscription.component.hosted': 'Merchant Hosted',
    'subscription.component.managedPlan': 'PayerMax Managed Plan',
    'subscription.component.planCreated': 'Subscription plan created',
    'subscription.component.planHint': '组件 Session 已预取。选择支付方式加载组件，获取 paymentToken 后继续激活。',
    'subscription.component.selectMethod': 'Select Method',
    'subscription.component.sessionPreparing': 'Component session is preparing...',
    'subscription.component.cardHint': '真实卡信息由组件收集，商户前端只拿 paymentToken。',
    'subscription.component.walletPreparing': 'Wallet component is preparing...',
    'subscription.component.methodReady': '{method} 组件已加载。点击底部按钮获取 paymentToken，用于后续 orderAndPay 激活订阅。',
    'subscription.component.waitSession': 'applySession 已完成后会动态挂载对应组件，当前正在等待 sessionKey/clientKey。',
    'subscription.component.sdkMissing': '当前未检测到 PMdropin SDK。演示环境可生成本地 token；真实接入时应展示 PayerMax 动态组件。',
    'subscription.component.tokenUsage': '将 paymentToken、sessionKey、subscriptionNo 用于后续 orderAndPay 激活订阅。',
    'subscription.component.copy': 'Copy',
    'subscription.component.copied': 'Copied',
    'subscription.component.submitToken': '获取TOKEN下单请求',
    'subscription.component.queryStatus': 'Query Subscription Status',
    'subscription.component.submitTokenOrder': 'Submit Token & Order',
    'subscription.component.deviceUnsupported': 'Device Unsupported',
    'subscription.component.applePayHint': 'Please use Safari or an iOS device',
    'subscription.component.tokenizeOrder': '获取 paymentToken',
    'subscription.component.confirmActivate': 'Confirm & Activate',
    'subscription.component.confirmAuth': 'Confirm Authorization',
    'subscription.bind.resultAction': '查看绑定结果',
    'subscription.bind.enterBound': '进入完成支付绑定',
    'subscription.bind.openCashier': '打开绑定收银台',
    'subscription.bind.cashierTitle': 'PayerMax 收银台绑定',
    'subscription.bind.firstBindingDesc': '首次绑定需要用户参与授权，固定传 merchantInitiated=false，并生成后续扣款使用的 paymentTokenID。',
    'subscription.bind.apiRedirect': '调用 orderAndPay 获取 redirectUrl 并打开收银台',
    'subscription.bind.apiHint': 'API 模式下，商户页面负责收集支付信息，用于后续调用 orderAndPay。',
    'subscription.bind.successToken': '绑定成功 · paymentTokenID',
    'subscription.order.firstTitle': '首次绑定下单',
    'subscription.order.queryAfterAuth': '授权完成后，查询绑定结果',
    'subscription.order.orderDesc': '将上一步收集的支付要素用于 orderAndPay。',
    'subscription.order.tokenUsage': '将 paymentToken、sessionKey、subscriptionNo 用于后续 orderAndPay 激活订阅。',
    'subscription.order.needToken': '请先在上一步完成前置组件授权，获取 paymentToken 与 sessionKey。',
    'subscription.order.callFirstBind': '调用 orderAndPay 首次绑定',
    'subscription.bound.title': '完成支付绑定',
    'subscription.bound.confirmed': '绑定结果已确认',
    'subscription.bound.desc': '已查询首次绑定结果。商户需保管 paymentTokenID，用于后续扣款。',
    'subscription.bound.waitToken': '等待 orderQuery 返回 paymentTokenID',
    'subscription.bound.waitOrder': '等待首次绑定订单号',
    'subscription.bound.nextDebit': '进入后续扣款',
    'subscription.deduct.title': '后续商户扣款',
    'subscription.deduct.desc': '后续商家利用 paymentTokenID 调用 orderAndPay 接口进行扣款。',
    'subscription.deduct.amount': '扣款金额',
    'subscription.deduct.waitToken': '请先完成首次绑定并通过 orderQuery 获取 paymentTokenID',
    'subscription.deduct.boundDone': '绑定结果已完成',
    'subscription.deduct.reset': '支付完成，重置流程',
    'subscription.complete.unit.D': '日',
    'subscription.complete.unit.W': '周',
    'subscription.complete.unit.M': '月',
    'subscription.complete.unit.Y': '年',
    'subscription.complete.fullCashier': '全量收银台',
    'subscription.complete.periodText': '每 {count} {unit} · 共 {total} 期',
    'subscription.complete.plan.standard': '普通订阅',
    'subscription.complete.plan.trial': '{days} 天免费试用',
    'subscription.complete.plan.discount': '前 {count} 期优惠',
    'subscription.complete.plan.trialDiscount': '{days} 天试用 + 前 {count} 期优惠',
    'subscription.complete.rule.trial': '试用期 {days} 天，激活金额 {amount}',
    'subscription.complete.rule.discount': '优惠期 {count} 期，每期 {amount}',
    'subscription.complete.rule.later': '后续每期 {amount}',
    'subscription.complete.title.active': '订阅激活成功',
    'subscription.complete.title.failed': '订阅激活失败',
    'subscription.complete.title.pending': '订阅状态待确认',
    'subscription.complete.desc.active': '订阅计划已创建并完成首次激活，后续扣款由约定周期驱动。',
    'subscription.complete.desc.failed': 'subscriptionQuery 返回状态为 {status}，请根据查询结果排查首期授权/支付。',
    'subscription.complete.desc.pending': 'subscriptionQuery 返回状态为 {status}，请等待异步结果或重新查询。',
    'subscription.complete.planLabel': '订阅方案',
    'subscription.complete.periodLabel': '扣款周期',
    'subscription.complete.ruleLabel': '订阅规则',
    'subscription.complete.activationLabel': '激活请求',
    'subscription.complete.queryLabel': '查询状态',
    'subscription.complete.methodLabel': '支付方式',
    'subscription.complete.reset': '重置订阅流程',
    'subscription.activate.checkResult': '查看支付结果',
    'subscription.activate.querying': '正在查询订阅状态',
    'subscription.activate.queryAfterAuth': '授权完成后，查询订阅状态',
    'subscription.activate.queryReturned': '授权页面已返回，正在调用 subscriptionQuery 获取真实激活结果。',
    'subscription.activate.requestingOrder': '正在请求 orderAndPay',
    'subscription.activate.queryDesc': '正在调用 subscriptionQuery，并在最后一步展示真实订阅激活状态。',
    'subscription.activate.prepareTitle': '准备支付下单激活订阅',
    'subscription.activate.prepareDesc': '将第二步获得的 sessionKey 与 paymentToken 用于 orderAndPay 激活订阅。',
    'subscription.activate.callOrder': '调用 orderAndPay 激活订阅',
    'subscription.activate.orderReturnedDesc': 'orderAndPay 已返回，可查询订阅结果。',
    'subscription.activate.failedTitle': '激活请求未成功',
    'subscription.activate.failedDesc': '请查看左侧 orderAndPay 响应体中的错误原因。',
    'subscription.activate.waitTitle': '等待激活请求',
    'subscription.activate.waitDesc': '系统会根据上一步结果进入后续查询。',
    'subscription.activate.orderStatus': 'orderAndPay 状态',
    'subscription.activate.noteAuthDone': '用户完成授权/3DS 后，手动查询订阅状态。',
    'subscription.activate.noteComponentReturned': '组件模式 orderAndPay 已返回，手动查询订阅状态。',
    'subscription.activate.noteOrderReturned': 'orderAndPay 已返回，用户点击后查询订阅激活结果。',
    'subscription.drama.genre': 'Thriller · Romance · 100+ Eps',
    'subscription.drama.selectOffer': 'Select Your Offer',
    'subscription.drama.monthlyPlan': 'Monthly Plan',
    'subscription.drama.trialTitle': '7-Day Free Access',
    'subscription.drama.trialBadge': 'Trial',
    'subscription.drama.trialDesc': '试用期间 0 元扣费。结束后按每月 {currency} {amount} 自动续费。',
    'subscription.drama.discountTitle': 'Introductory Offer',
    'subscription.drama.discountBadge': 'Save 33%',
    'subscription.drama.discountDesc': '前 {count} 个月仅需 {currency} {amount}，后续恢复原价。',
    'subscription.drama.comboTitle': 'Double Combo Strategy',
    'subscription.drama.comboBadge': 'Best Value',
    'subscription.drama.comboDesc': '7天试用 + 前3个月特惠，全方位营销方案体验。',
    'subscription.drama.startTrial': 'START {days}-DAY FREE TRIAL',
    'subscription.drama.subscribe': 'SUBSCRIBE & UNLOCK ALL',
    'subscription.drama.cancelAnytime': 'Cancel Anytime',
    'subscription.drama.onlyStart': 'Only {currency} {amount} to start',
    'subscription.router.unknown': '未知步骤 ID',
    'subscription.toast.needComponentTokenRequest': '请先在右侧仿真手机内完成前置组件授权，获取 paymentToken 后再执行请求。',
    'subscription.toast.needComponentPaymentToken': '请先在右侧仿真手机内选择支付方式并获取 paymentToken。paymentToken 只能由组件授权后返回。',
    'subscription.toast.needBindOrder': '请先完成首次绑定下单，拿到真实订单号后再查询绑定结果。',
    'subscription.toast.needMandateToken': '请先完成首次绑定并通过 orderQuery 获取 paymentTokenID，再发起后续扣款。',
    'subscription.toast.apmComponentFallback': 'APM 支付方式暂不支持前置组件，已自动切换为收银台模式。',
    'subscription.toast.apmComponentUnsupported': 'APM 支付方式暂不支持前置组件，请选择其他支付方式或集成方式。',
    'subscription.toast.needOrderAndPayToken': '请先在右侧仿真手机内完成前置组件授权，获取 paymentToken 后再执行 orderAndPay。',
    'subscription.toast.needSubscriptionPlan': '请先创建订阅计划，再执行前置组件激活下单。',
    'subscription.toast.needComponentAuth': '请先在右侧仿真手机内完成前置组件授权并获取 paymentToken。',
    'subscription.toast.needFirstBindToken': '请先在右侧仿真手机内完成前置组件授权，获取 paymentToken 后再执行首次绑定下单。',
    'subscription.toast.componentMissing': '组件实例不存在：{method} 尚未完成挂载，请重新选择支付方式或刷新页面后重试。',
    'subscription.toast.tokenBusy': '正在处理上一笔 {method} token 请求，请等待组件返回后再点击。',
    'subscription.toast.canMakePaymentTimeout': '{method} canMakePayment 15秒未返回，可能是钱包弹窗未拉起、浏览器环境不支持，或 SDK 内部未触发回调。',
    'subscription.error.createMissingNo': '创建订阅失败：未返回 subscriptionNo',
    'subscription.error.missingSubscriptionNoCreate': '订阅号不存在，请先创建订阅计划',
    'subscription.error.missingSubscriptionNoQuery': '订阅号不存在，无法查询订阅状态',
    'subscription.error.activateFailed': '激活订阅失败',
    'subscription.error.tokenFailed': '获取 {method} paymentToken 失败：{reason}',
    'subscription.error.tokenException': '获取 {method} paymentToken 异常：{reason}',
    'subscription.error.firstBindFailed': '首次绑定下单失败：{reason}',
    'subscription.error.unsupportedAmount': '当前支付方式或渠道可能不支持该首次绑定金额。可切换“首次 >0 元绑定”，或更换支付方式后再验证。',
    'link.config.apiTitle': '商品参数 / 创建链接',
    'link.config.dashboardTitle': '商户后台生成链接',
    'link.product': '商品名称',
    'link.type': '链接类型',
    'link.country': '收单国家',
    'link.amount': '订单金额',
    'link.expires': '有效期',
    'link.seconds': '秒',
    'link.apiHint': '点击创建链接后，请求创建链接接口，下一步把 linkUrl 与 qrCodeUrl 交给用户完成支付。',
    'link.dashboardHint': '商户在 PayerMax 后台录入订单信息并生成链接，再把二维码或链接分发给用户。',
    'link.create': '创建支付链接',
    'link.generate': '模拟生成链接',
    'link.opening': '正在打开支付链接',
    'link.openingHint': '先尝试在仿真手机内展示，若页面无法加载会自动使用新窗口打开。',
    'link.openNewWindow': '新窗口打开',
    'link.queryAfterPay': '支付完成后查询链接状态',
    'link.opened': '支付链接已打开',
    'link.openedHint': '真实支付页已在浏览器新窗口打开。用户完成支付后，返回本演示查询链接状态。',
    'link.userPaymentTitle': '扫码或打开链接支付',
    'link.returned': 'createPaybylink 已返回',
    'link.returnedHint': '商户可将二维码或链接分发给用户。点击下方按钮后，在本仿真手机内打开 PayerMax 链接支付页。',
    'link.openPayment': '打开链接去支付',
    'link.resultTitle': '链接结果查询',
    'link.resultHint': '通过 queryPaybylink 查看链接状态和支付信息。',
    'link.merchantNotes': '生产环境中，支付结果应优先以异步通知验签入账；查询接口用于补偿确认和商户后台展示。',
    'link.createNew': '重新生成支付链接',
    'link.toast.needUserPayment': '请确认用户已在右侧仿真手机打开链接并完成支付后，再查询链接状态。',
    'link.dashboardGuide.stepCreate': '创建链接',
    'link.dashboardGuide.stepCreateDesc': '登录 PayerMax 商户平台（MMC），进入收单产品 → 链接支付 → 创建链接。',
    'link.dashboardGuide.stepInput': '录入订单信息',
    'link.dashboardGuide.stepInputDesc': '填写商品名称、订单金额、收单国家、有效期等一次性支付链接参数。',
    'link.dashboardGuide.stepGenerate': '生成链接 / 二维码',
    'link.dashboardGuide.stepGenerateDesc': 'MMC 自动生成支付链接与二维码，商户可复制链接或下载二维码。',
    'link.dashboardGuide.stepSend': '发送至用户完成支付',
    'link.dashboardGuide.stepSendDesc': '用户打开链接或扫码完成支付，支付后可通过 MMC 或 API 查询结果。',
    'link.dashboardGuide.badgeProduct': '链接支付',
    'link.dashboardGuide.badgeDashboard': 'MMC 创建',
    'link.dashboardGuide.title': '商户后台创建一次性支付链接',
    'link.dashboardGuide.desc': 'PayerMax 允许商户登录商户平台（MMC）创建一次性支付链接并生成二维码，适合人工录单、客服收款、线下分发等场景。',
    'link.dashboardGuide.pathProduct': '收单产品',
    'link.dashboardGuide.pathLink': '链接支付',
    'link.dashboardGuide.pathCreate': '创建链接',
    'link.dashboardGuide.stepsTitle': '四步完成后台创建',
    'link.dashboardGuide.stepsDesc': '该模式不需要调用创建接口，也不需要仿真手机演示；商户按 MMC 页面指引录入信息即可。',
    'link.dashboardGuide.noApi': '无需开发创建接口',
    'link.dashboardGuide.queryTitle': '支付结果查询',
    'link.dashboardGuide.queryDesc': '用户支付完成后，商户可登录 MMC 查看结果，也可以使用 API 主动查询订单状态；展示给用户前应以查询或回调结果为准。',
    'step.standard.cashier.ALL.s1': '商品信息',
    'step.standard.cashier.ALL.s2': '下单展示',
    'step.standard.cashier.ALL.s3': '支付成功',
    'step.standard.cashier.SPECIFIC.s1': '商品 / 自建收银台',
    'step.standard.cashier.SPECIFIC.s2': '下单展示',
    'step.standard.cashier.SPECIFIC.s3': '支付成功',
    'step.standard.api.ALL.s1': '商品 / 自建收银台',
    'step.standard.api.ALL.s2': '下单支付',
    'step.standard.api.ALL.s3': '支付成功',
    'step.standard.component.ALL.s1': '商品信息',
    'step.standard.component.ALL.s2': '自建收银台',
    'step.standard.component.ALL.s3': '下单支付',
    'step.standard.component.ALL.s4': '支付成功',
    'step.link.api.l1': '商品参数 / 创建链接',
    'step.link.dashboard.l1': '后台录入 / 生成链接',
    'step.link.l2': '用户支付',
    'step.link.l3': '查询结果',
    'step.subscription.pm-1.title': '配置订阅参数',
    'step.subscription.pm-1.hint': '配置 PayerMax 托管订阅计划的套餐、周期和金额',
    'step.subscription.pm-2.title': '创建订阅计划',
    'step.subscription.pm-2.hint': '前端 JS 调用 subscriptionCreate 创建订阅计划',
    'step.subscription.pm-2.component.title': '创建计划与自建收银台',
    'step.subscription.pm-2.component.hint': '前端 JS 创建订阅计划并预取组件 Session，手机内展示商户自建收银台获取 paymentToken',
    'step.subscription.pm-component.title': '支付下单激活订阅',
    'step.subscription.pm-component.hint': '前端 JS 使用 paymentToken 调用 orderAndPay，展示真实请求、响应以及可能返回的 3DS/redirectUrl',
    'step.subscription.pm-activate.title': '激活订阅',
    'step.subscription.pm-activate.hint': '调用 orderAndPay 完成首次授权/支付激活',
    'step.subscription.pm-complete.title': '完成订阅激活',
    'step.subscription.pm-complete.hint': '通过 subscriptionQuery 查询并展示真实订阅激活结果',
    'step.subscription.m-1.title': '配置绑定参数',
    'step.subscription.m-1.hint': '商户自管周期性订阅：商户自行管理扣款周期，首次绑定生成 token',
    'step.subscription.m-1.api.title': '配置参数 / 自建收银台',
    'step.subscription.m-1.api.hint': '先展示商户收集的绑定参数，再在同一步进入自建收银台选择支付方式',
    'step.subscription.m-component.title': '自建收银台获取 token',
    'step.subscription.m-component.hint': '加载前置组件获取 paymentToken，仅完成前端收集要素',
    'step.subscription.m-order.title': '首次绑定下单',
    'step.subscription.m-order.hint': '前端 JS 调用 orderAndPay 完成首次绑定，并展示真实请求和响应',
    'step.subscription.m-bind.title': '首次绑定支付方式',
    'step.subscription.m-bind.hint': '收银台模式跳转 PayerMax，并通过 orderAndPay 返回 redirectUrl',
    'step.subscription.m-bound.title': '完成支付绑定',
    'step.subscription.m-bound.hint': '调用 orderQuery 查询首次绑定结果，并提示商户保存 paymentTokenID',
    'step.subscription.m-deduct.title': '后续发起扣款',
    'step.subscription.m-deduct.hint': '商户按订阅周期使用 paymentTokenID 自行发起扣款',
    'step.subscription.np-1.title': '收集业务数据',
    'step.subscription.np-1.hint': '非周期性代扣：商户按需扣款，首次绑定传 UNSCHEDULED 并生成 token',
    'step.subscription.np-1.api.title': '收集数据 / 自建收银台',
    'step.subscription.np-1.api.hint': '先展示商户收集的业务数据，再在同一步进入自建收银台选择支付方式',
    'step.subscription.np-component.title': '自建收银台获取 token',
    'step.subscription.np-component.hint': '加载前置组件获取 paymentToken，仅完成前端收集要素',
    'step.subscription.np-order.title': '首次绑定下单',
    'step.subscription.np-order.hint': '前端 JS 调用 orderAndPay 完成首次绑定，并展示真实请求和响应',
    'step.subscription.np-bind.title': '首次绑定支付方式',
    'step.subscription.np-bind.hint': '收银台模式跳转 PayerMax，并通过 orderAndPay 返回 redirectUrl',
    'step.subscription.np-bound.title': '完成支付绑定',
    'step.subscription.np-bound.hint': '调用 orderQuery 查询首次绑定结果，并提示商户保存 paymentTokenID',
    'step.subscription.np-deduct.title': '后续发起扣款',
    'step.subscription.np-deduct.hint': '商户按业务需要使用 paymentTokenID 灵活发起扣款',
  },
  'en-US': {
    'language.title': 'Language',
    'language.zh': '中文',
    'language.en': 'EN',
    'common.prevStep': 'Previous',
    'common.pciApiPrerequisite': 'Prerequisite: PCI qualification is required to use API integration.',
    'mode.STANDARD': 'Standard Payment',
    'mode.SUBSCRIPTION': 'Subscription',
    'mode.PAYMENT_LINK': 'Pay by Link',
    'sidebar.subscriptionConfig': 'Subscription Config',
    'sidebar.paymentConfiguration': 'Payment Configuration',
    'sidebar.businessMode': 'Business Mode',
    'sidebar.integrationMode': 'Integration Mode',
    'sidebar.paymentMethod': 'Payment Method',
    'sidebar.paymentConfig': 'Payment Config',
    'sidebar.resetAllSteps': '↻ Reset All Steps',
    'sidebar.chooseMode': 'Please select a business mode from the top bar',
    'sidebar.allCashier': 'All Cashier',
    'sidebar.cashierAll': 'All Cashier',
    'sidebar.cashierSpecific': 'Specific Method',
    'sidebar.managedByPayerMax': 'MANAGED BY PAYERMAX',
    'sidebar.fullCashierHint1': '• No payment method is required in All Cashier mode',
    'sidebar.fullCashierHint2': '• End users choose a method on the PayerMax page',
    'sidebar.standardTip': 'Switch integration modes to update the API request view on the right.',
    'sidebar.linkTip': 'Pay by Link supports manual dashboard creation and automated API distribution.',
    'sidebar.apmTipLine1': 'APM subscription activation uses ONE_TOUCH and defaults targetOrg to KAKAOPAY.',
    'sidebar.apmTipLine2': 'This demo is fixed to KR / KRW.',
    'subMode.payermax.name': 'PayerMax Manage Subscription Plans',
    'subMode.payermax.desc': 'PayerMax manages the plan and billing cycle',
    'subMode.merchant.name': 'Merchants Manage Subscription Plans',
    'subMode.merchant.desc': 'Merchants manage the plan and debit timing',
    'subMode.nonperiodic.name': 'Non-Periodic Auto Debit',
    'subMode.nonperiodic.desc': 'Merchants initiate auto debits based on business needs',
    'integration.cashier': 'Cashier Payment / Activation',
    'integration.api': 'Direct API / Activation',
    'integration.component': 'Drop In / Activation',
    'paymentIntegration.cashier.label': 'Cashier Payment',
    'paymentIntegration.cashier.desc': 'Redirect users to the PayerMax hosted cashier to complete payment',
    'paymentIntegration.api.label': 'Direct API',
    'paymentIntegration.api.desc': 'Fully control the payment UI in the merchant page',
    'paymentIntegration.component.label': 'Drop In',
    'paymentIntegration.component.desc': 'Embed a lightweight PayerMax payment component in the merchant page',
    'linkMode.dashboard.label': 'Create Link in Dashboard',
    'linkMode.dashboard.desc': 'Create links or QR codes in PayerMax Merchant Center without calling the create API.',
    'linkMode.api.label': 'Create Link by API',
    'linkMode.api.desc': 'Generate pay links dynamically via createPaybylink for automation and batch distribution.',
    'code.note.standard': 'The first frontend step collects product, user, and payment selections for later PayerMax API requests.',
    'code.note.subscription': 'The first frontend step collects subscription and auto debit parameters for later PayerMax API requests.',
    'code.note.link': 'The first frontend step collects pay link product parameters for creating the payment link.',
    'code.next.standard.order': 'Create a payment order with orderAndPay',
    'code.next.standard.component': 'Get sessionKey with applySession or create the order with orderAndPay',
    'code.next.link': 'createPaybylink returns linkUrl and qrCodeUrl',
    'code.next.subscription.payermax': 'Create a PayerMax managed subscription plan with subscriptionCreate',
    'code.next.subscription.mandate': 'Bind the payment method with orderAndPay and get paymentTokenID for later debits',
    'code.empty': 'Real request and response will appear after this step.',
    'result.orderReturned': 'orderAndPay Returned',
    'result.api': 'API',
    'result.paymentMethod': 'Payment Method',
    'result.status': 'Status',
    'result.check': 'Check Result',
    'result.returnReceived': 'Return Received',
    'result.orderNo': 'Order No.',
    'standard.checkout.3dsComplete': '3DS Complete',
    'standard.checkout.paymentComplete': 'Payment Complete',
    'standard.checkout.requestingOrder': 'Requesting orderAndPay',
    'standard.checkout.orderDisplay': 'Order Display',
    'standard.checkout.cashierPayment': 'Cashier Payment',
    'standard.checkout.requestSent': '',
    'standard.checkout.processingPayment': 'Processing payment request.',
    'standard.checkout.cashierLoading': 'PayerMax cashier is loading.',
    'standard.checkout.waitingResult': 'Waiting Result',
    'standard.component.paymentComplete': 'Payment Complete',
    'standard.component.readyOrder': 'Ready for orderAndPay',
    'standard.component.useToken': 'Use paymentToken and sessionKey to create the payment order.',
    'standard.component.tokenReadyHint': 'Token is ready for the next order step.',
    'standard.component.callOrder': 'Call orderAndPay',
    'standard.toast.needSelfCashierSelection': 'Tap Buy Now in the phone and select a payment method first.',
    'standard.toast.needComponentAuth': 'Select a method and get paymentToken in the phone first.',
    'standard.toast.needComponentToken': 'Get paymentToken in the self-hosted cashier before orderAndPay.',
    'standard.toast.needPaymentMethod': 'Select a payment method in the phone first.',
    'standard.error.sessionFailed': 'Session failed',
    'standard.error.networkFailed': 'Network request failed. Check service status.',
    'standard.error.paymentFailed': 'Payment failed: {reason}',
    'standard.error.orderFailed': 'Order failed: {reason}',
    'standard.error.browserDirectFailed': 'Browser direct request to PayerMax failed',
    'standard.error.browserDirectFailedFull': 'Browser direct request failed. Check network, CORS, or signature.',
    'standard.error.missingOrderQuery': 'Missing orderQuery parameters',
    'subscription.config.planTitle': 'Plan',
    'subscription.config.planDesc': 'PayerMax manages the plan and recurring debits.',
    'subscription.config.merchantTitle': 'Merchant Rules',
    'subscription.config.merchantDesc': 'PayerMax returns paymentTokenID. The merchant manages cycles and amounts.',
    'subscription.config.nonperiodicTitle': 'Auto Debit Rules',
    'subscription.config.nonperiodicDesc': 'Store paymentTokenID after binding. Debits are triggered as needed.',
    'subscription.config.parameters': 'Parameters',
    'subscription.config.apmFixed': 'APM is fixed to KR / KRW in this demo.',
    'subscription.config.totalPeriods': 'Periods',
    'subscription.config.periodCount': 'Frequency',
    'subscription.config.periodUnit': 'Unit',
    'subscription.config.unit.D': 'Day',
    'subscription.config.unit.W': 'Week',
    'subscription.config.unit.M': 'Month',
    'subscription.config.unit.Y': 'Year',
    'subscription.config.amount': 'Amount',
    'subscription.config.currency': 'Currency',
    'subscription.config.trialDays': 'Trial Days',
    'subscription.config.discountPeriods': 'Discount Periods',
    'subscription.config.discountAmount': 'Discount Amount',
    'subscription.config.laterPlanAmount': 'Later Debit Amount',
    'subscription.config.firstAndLaterAmount': 'First & Later Amount',
    'subscription.config.laterOnDemandAmount': 'Later Debit Amount',
    'subscription.config.subject': 'Subject',
    'subscription.config.userId': 'User ID',
    'subscription.config.firstBindType': 'First Binding Type',
    'subscription.config.zeroBind': 'Zero-Amount Binding',
    'subscription.config.paidBind': 'Paid Binding',
    'subscription.config.zeroBindDesc': 'Authorize and get token',
    'subscription.config.paidBindDesc': 'Bind and charge first payment',
    'subscription.config.firstAmount': 'First Amount',
    'subscription.config.firstBindAmount': 'First Amount',
    'subscription.config.laterDebitAmount': 'Later Amount',
    'subscription.config.mitType': 'MIT Type',
    'subscription.config.trialScenario': 'Trial',
    'subscription.config.firstPayScenario': 'First Pay',
    'subscription.config.zeroMerchantDesc': 'User authorizes first. Merchant debits after trial.',
    'subscription.config.zeroNonperiodicDesc': 'User authorizes first. Merchant debits on demand.',
    'subscription.config.paidMerchantDesc': 'First payment is completed during binding.',
    'subscription.config.paidNonperiodicDesc': 'First charge is collected, then token is kept for later debits.',
    'subscription.config.merchantPreviewTitle': 'Merchant Subscription',
    'subscription.config.nonperiodicPreviewTitle': 'Non-Periodic Auto Debit',
    'subscription.config.previewHint': 'Choose the first binding amount type.',
    'subscription.config.nextOrderHint': 'Next: call orderAndPay to complete binding.',
    'subscription.config.firstOrderBind': 'Create Binding Order',
    'subscription.type.standard.label': 'Standard',
    'subscription.type.standard.desc': 'Amount > 0',
    'subscription.type.trial.label': 'Trial',
    'subscription.type.trial.desc': 'Amount = 0',
    'subscription.type.discount.label': 'Discount',
    'subscription.type.discount.desc': 'Amount > 0',
    'subscription.type.trial_discount.label': 'Trial + Discount',
    'subscription.type.trial_discount.desc': 'Combined offer',
    'subscription.create.title': 'Create Plan',
    'subscription.create.creating': 'Creating Plan...',
    'subscription.create.calling': 'Calling subscriptionCreate',
    'subscription.create.success': 'Plan Created',
    'subscription.create.inactive': 'Status: INACTIVE. Activation is required next.',
    'subscription.create.preparingSession': 'Preparing Component Session...',
    'subscription.create.sessionReady': 'Session Ready',
    'subscription.create.sessionReadyHint': 'Components will load by selected method.',
    'subscription.create.requestingOrder': 'Requesting orderAndPay',
    'subscription.create.enterCashier': 'Enter Cashier',
    'subscription.create.activate': 'Activate Subscription',
    'subscription.create.retry': 'Retry',
    'subscription.create.errorCreate': 'Create plan failed',
    'subscription.create.errorSession': 'Session failed',
    'subscription.create.errorActivate': 'Activation failed',
    'subscription.component.hosted': 'Merchant Hosted',
    'subscription.component.managedPlan': 'PayerMax Managed Plan',
    'subscription.component.planCreated': 'Subscription plan created',
    'subscription.component.planHint': 'Session ready. Select a method, get paymentToken, then activate.',
    'subscription.component.selectMethod': 'Select Method',
    'subscription.component.sessionPreparing': 'Preparing session...',
    'subscription.component.cardHint': 'Card details are collected by the component.',
    'subscription.component.walletPreparing': 'Preparing wallet...',
    'subscription.component.methodReady': '{method} ready. Tap the bottom button to get paymentToken.',
    'subscription.component.waitSession': 'Waiting for sessionKey/clientKey.',
    'subscription.component.sdkMissing': 'PMdropin SDK not detected. Demo can generate a local token.',
    'subscription.component.tokenUsage': 'Use paymentToken, sessionKey, and subscriptionNo for orderAndPay.',
    'subscription.component.copy': 'Copy',
    'subscription.component.copied': 'Copied',
    'subscription.component.submitToken': 'Submit Token',
    'subscription.component.queryStatus': 'Query Subscription Status',
    'subscription.component.submitTokenOrder': 'Submit Token & Order',
    'subscription.component.deviceUnsupported': 'Device Unsupported',
    'subscription.component.applePayHint': 'Please use Safari or an iOS device',
    'subscription.component.tokenizeOrder': 'Get paymentToken',
    'subscription.component.confirmActivate': 'Confirm & Activate',
    'subscription.component.confirmAuth': 'Confirm Authorization',
    'subscription.bind.resultAction': 'View Binding Result',
    'subscription.bind.enterBound': 'Complete Binding',
    'subscription.bind.openCashier': 'Open Cashier',
    'subscription.bind.cashierTitle': 'PayerMax Cashier Binding',
    'subscription.bind.firstBindingDesc': 'User authorizes first. paymentTokenID is generated for later debits.',
    'subscription.bind.apiRedirect': 'Call orderAndPay to get redirectUrl and open cashier',
    'subscription.bind.apiHint': 'Merchant page collects payment details for orderAndPay.',
    'subscription.bind.successToken': 'Bound · paymentTokenID',
    'subscription.order.firstTitle': 'First Binding Order',
    'subscription.order.queryAfterAuth': 'Query Binding Result',
    'subscription.order.orderDesc': 'Use collected payment details for orderAndPay.',
    'subscription.order.tokenUsage': 'Use paymentToken, sessionKey, and subscriptionNo for orderAndPay.',
    'subscription.order.needToken': 'Get paymentToken and sessionKey in the previous step first.',
    'subscription.order.callFirstBind': 'Call orderAndPay',
    'subscription.bound.title': 'Payment Binding Complete',
    'subscription.bound.confirmed': 'Binding Confirmed',
    'subscription.bound.desc': 'First binding result queried. Store paymentTokenID for later debits.',
    'subscription.bound.waitToken': 'Waiting for paymentTokenID',
    'subscription.bound.waitOrder': 'Waiting for bind order No.',
    'subscription.bound.nextDebit': 'Continue to Debit',
    'subscription.deduct.title': 'Subsequent Merchant Debit',
    'subscription.deduct.desc': 'Merchant uses paymentTokenID to call orderAndPay for later debits.',
    'subscription.deduct.amount': 'Debit Amount',
    'subscription.deduct.waitToken': 'Complete first binding and query paymentTokenID first',
    'subscription.deduct.boundDone': 'Binding Completed',
    'subscription.deduct.reset': 'Reset Flow',
    'subscription.complete.unit.D': 'day',
    'subscription.complete.unit.W': 'week',
    'subscription.complete.unit.M': 'month',
    'subscription.complete.unit.Y': 'year',
    'subscription.complete.fullCashier': 'All Cashier',
    'subscription.complete.periodText': 'Every {count} {unit} · {total} periods',
    'subscription.complete.plan.standard': 'Standard',
    'subscription.complete.plan.trial': '{days}-Day Trial',
    'subscription.complete.plan.discount': '{count}-Period Discount',
    'subscription.complete.plan.trialDiscount': '{days}-Day Trial + {count}-Period Discount',
    'subscription.complete.rule.trial': 'Trial {days} days, activation {amount}',
    'subscription.complete.rule.discount': 'Discount {count} periods, {amount} each',
    'subscription.complete.rule.later': 'Later {amount} per period',
    'subscription.complete.title.active': 'Subscription Activated',
    'subscription.complete.title.failed': 'Activation Failed',
    'subscription.complete.title.pending': 'Status Pending',
    'subscription.complete.desc.active': 'Plan is created and activated. Later debits follow the cycle.',
    'subscription.complete.desc.failed': 'subscriptionQuery returned {status}. Check the first authorization/payment.',
    'subscription.complete.desc.pending': 'subscriptionQuery returned {status}. Wait or query again.',
    'subscription.complete.planLabel': 'Plan',
    'subscription.complete.periodLabel': 'Cycle',
    'subscription.complete.ruleLabel': 'Rule',
    'subscription.complete.activationLabel': 'Activation',
    'subscription.complete.queryLabel': 'Query Status',
    'subscription.complete.methodLabel': 'Payment Method',
    'subscription.complete.reset': 'Reset Subscription',
    'subscription.activate.checkResult': 'Check Result',
    'subscription.activate.querying': 'Querying Status',
    'subscription.activate.queryAfterAuth': 'Query Status',
    'subscription.activate.queryReturned': 'Authorization returned. Querying subscription status.',
    'subscription.activate.requestingOrder': 'Requesting orderAndPay',
    'subscription.activate.queryDesc': 'Calling subscriptionQuery and showing the final result next.',
    'subscription.activate.prepareTitle': 'Ready to Activate',
    'subscription.activate.prepareDesc': 'Use sessionKey and paymentToken for orderAndPay.',
    'subscription.activate.callOrder': 'Call orderAndPay',
    'subscription.activate.orderReturnedDesc': 'orderAndPay returned. Query result next.',
    'subscription.activate.failedTitle': 'Activation Failed',
    'subscription.activate.failedDesc': 'Check the orderAndPay response on the left.',
    'subscription.activate.waitTitle': 'Waiting for Activation',
    'subscription.activate.waitDesc': 'The next query depends on the previous result.',
    'subscription.activate.orderStatus': 'orderAndPay Status',
    'subscription.activate.noteAuthDone': 'User completed authorization/3DS. Query subscription status manually.',
    'subscription.activate.noteComponentReturned': 'Component orderAndPay returned. Query subscription status manually.',
    'subscription.activate.noteOrderReturned': 'orderAndPay returned. User clicks to query the activation result.',
    'subscription.drama.genre': 'Thriller · Romance · 100+ Eps',
    'subscription.drama.selectOffer': 'Select Your Offer',
    'subscription.drama.monthlyPlan': 'Monthly Plan',
    'subscription.drama.trialTitle': '7-Day Free Access',
    'subscription.drama.trialBadge': 'Trial',
    'subscription.drama.trialDesc': 'Free for trial. Then {currency} {amount}/month.',
    'subscription.drama.discountTitle': 'Introductory Offer',
    'subscription.drama.discountBadge': 'Save 33%',
    'subscription.drama.discountDesc': '{count} months at {currency} {amount}, then regular price.',
    'subscription.drama.comboTitle': 'Double Combo Strategy',
    'subscription.drama.comboBadge': 'Best Value',
    'subscription.drama.comboDesc': '7-day trial plus 3 discounted months.',
    'subscription.drama.startTrial': 'START {days}-DAY FREE TRIAL',
    'subscription.drama.subscribe': 'SUBSCRIBE & UNLOCK ALL',
    'subscription.drama.cancelAnytime': 'Cancel Anytime',
    'subscription.drama.onlyStart': 'Only {currency} {amount} to start',
    'subscription.router.unknown': 'Unknown Step ID',
    'subscription.toast.needComponentTokenRequest': 'Complete component authorization in the phone and get paymentToken first.',
    'subscription.toast.needComponentPaymentToken': 'Select a method in the phone and get paymentToken first.',
    'subscription.toast.needBindOrder': 'Complete the first binding order before querying binding result.',
    'subscription.toast.needMandateToken': 'Get paymentTokenID from orderQuery before later debit.',
    'subscription.toast.apmComponentFallback': 'APM does not support Drop In. Switched to Cashier mode.',
    'subscription.toast.apmComponentUnsupported': 'APM does not support Drop In. Choose another method or integration.',
    'subscription.toast.needOrderAndPayToken': 'Get paymentToken in the phone before orderAndPay.',
    'subscription.toast.needSubscriptionPlan': 'Create the subscription plan before component activation order.',
    'subscription.toast.needComponentAuth': 'Complete component authorization and get paymentToken first.',
    'subscription.toast.needFirstBindToken': 'Get paymentToken in the phone before first binding order.',
    'subscription.toast.componentMissing': '{method} component is not mounted yet. Select the method again or refresh.',
    'subscription.toast.tokenBusy': '{method} token request is still processing. Please wait.',
    'subscription.toast.canMakePaymentTimeout': '{method} canMakePayment timed out. Wallet popup or SDK callback may be unavailable.',
    'subscription.error.createMissingNo': 'Create plan failed: subscriptionNo not returned',
    'subscription.error.missingSubscriptionNoCreate': 'Missing subscriptionNo. Create the plan first.',
    'subscription.error.missingSubscriptionNoQuery': 'Missing subscriptionNo. Cannot query status.',
    'subscription.error.activateFailed': 'Activation failed',
    'subscription.error.tokenFailed': 'Get {method} paymentToken failed: {reason}',
    'subscription.error.tokenException': 'Get {method} paymentToken error: {reason}',
    'subscription.error.firstBindFailed': 'First binding order failed: {reason}',
    'subscription.error.unsupportedAmount': 'This method or channel may not support the first binding amount. Try paid binding or another method.',
    'link.config.apiTitle': 'Create Link',
    'link.config.dashboardTitle': 'Dashboard Link',
    'link.product': 'Product',
    'link.type': 'Link Type',
    'link.country': 'Country',
    'link.amount': 'Amount',
    'link.expires': 'Expires',
    'link.seconds': 'sec',
    'link.apiHint': 'Create the link, then share linkUrl and qrCodeUrl with the user.',
    'link.dashboardHint': 'Create the link in PayerMax dashboard, then share the QR code or link.',
    'link.create': 'Create Link',
    'link.generate': 'Generate Link',
    'link.opening': 'Opening Link',
    'link.openingHint': 'Trying in-phone view first.',
    'link.openNewWindow': 'Open New Window',
    'link.queryAfterPay': 'Query Link Status',
    'link.opened': 'Payment Link Opened',
    'link.openedHint': 'The payment page opened in a new window. Return here to query status.',
    'link.userPaymentTitle': 'Scan or Open Link',
    'link.returned': 'createPaybylink Returned',
    'link.returnedHint': 'Share the QR code or link with the user, then open it in the phone simulator.',
    'link.openPayment': 'Open Payment Link',
    'link.resultTitle': 'Link Result',
    'link.resultHint': 'Queried by queryPaybylink.',
    'link.merchantNotes': 'Use async notification as the source of truth. Query API is for confirmation.',
    'link.createNew': 'Create New Link',
    'link.toast.needUserPayment': 'Open the link in the phone and complete payment before querying status.',
    'link.dashboardGuide.stepCreate': 'Create Link',
    'link.dashboardGuide.stepCreateDesc': 'Log in to PayerMax Merchant Center (MMC), then go to Acquiring Products → Pay by Link → Create Link.',
    'link.dashboardGuide.stepInput': 'Enter Order Info',
    'link.dashboardGuide.stepInputDesc': 'Fill in product name, amount, acquiring country, expiry time, and other one-time link parameters.',
    'link.dashboardGuide.stepGenerate': 'Generate Link / QR Code',
    'link.dashboardGuide.stepGenerateDesc': 'MMC generates the payment link and QR code. The merchant can copy the link or download the QR code.',
    'link.dashboardGuide.stepSend': 'Send to User',
    'link.dashboardGuide.stepSendDesc': 'The user opens the link or scans the QR code to pay. The result can be checked by MMC or API.',
    'link.dashboardGuide.badgeProduct': 'Pay by Link',
    'link.dashboardGuide.badgeDashboard': 'MMC Create',
    'link.dashboardGuide.title': 'Create a one-time payment link in MMC',
    'link.dashboardGuide.desc': 'Merchants can create one-time payment links and QR codes in PayerMax Merchant Center. This works well for manual order entry, support-assisted collection, and offline distribution.',
    'link.dashboardGuide.pathProduct': 'Acquiring Products',
    'link.dashboardGuide.pathLink': 'Pay by Link',
    'link.dashboardGuide.pathCreate': 'Create Link',
    'link.dashboardGuide.stepsTitle': 'Create in four steps',
    'link.dashboardGuide.stepsDesc': 'This mode does not call the create API or use the phone simulator. The merchant only follows the MMC page flow to enter order information.',
    'link.dashboardGuide.noApi': 'No create API needed',
    'link.dashboardGuide.queryTitle': 'Payment Result Query',
    'link.dashboardGuide.queryDesc': 'After payment, the merchant can view the result in MMC or query the order status by API. Use query or callback results before showing final status to users.',
    'step.standard.cashier.ALL.s1': 'Product Info',
    'step.standard.cashier.ALL.s2': 'Order Display',
    'step.standard.cashier.ALL.s3': 'Payment Success',
    'step.standard.cashier.SPECIFIC.s1': 'Product / Self-hosted Cashier',
    'step.standard.cashier.SPECIFIC.s2': 'Order Display',
    'step.standard.cashier.SPECIFIC.s3': 'Payment Success',
    'step.standard.api.ALL.s1': 'Product / Self-hosted Cashier',
    'step.standard.api.ALL.s2': 'Create Payment',
    'step.standard.api.ALL.s3': 'Payment Success',
    'step.standard.component.ALL.s1': 'Product Info',
    'step.standard.component.ALL.s2': 'Self-hosted Cashier',
    'step.standard.component.ALL.s3': 'Create Payment',
    'step.standard.component.ALL.s4': 'Payment Success',
    'step.link.api.l1': 'Product Params / Create Link',
    'step.link.dashboard.l1': 'Dashboard Entry / Generate Link',
    'step.link.l2': 'User Payment',
    'step.link.l3': 'Query Result',
    'step.subscription.pm-1.title': 'Configure Subscription',
    'step.subscription.pm-1.hint': 'Configure the package, cycle, and amount for the PayerMax managed subscription plan',
    'step.subscription.pm-2.title': 'Create Subscription Plan',
    'step.subscription.pm-2.hint': 'Frontend JS calls subscriptionCreate to create the subscription plan',
    'step.subscription.pm-2.component.title': 'Create Plan & Self-hosted Cashier',
    'step.subscription.pm-2.component.hint': 'Frontend JS creates the subscription plan, prefetches the component session, and the phone shows a self-hosted cashier to get paymentToken',
    'step.subscription.pm-component.title': 'Activate Subscription by Order',
    'step.subscription.pm-component.hint': 'Frontend JS uses paymentToken to call orderAndPay and displays the real request, response, and possible 3DS/redirectUrl',
    'step.subscription.pm-activate.title': 'Activate Subscription',
    'step.subscription.pm-activate.hint': 'Call orderAndPay to complete the first authorization or payment activation',
    'step.subscription.pm-complete.title': 'Complete Activation',
    'step.subscription.pm-complete.hint': 'Query and display the real subscription activation result via subscriptionQuery',
    'step.subscription.m-1.title': 'Configure Binding Params',
    'step.subscription.m-1.hint': 'Merchants manage billing cycles; first binding generates a token',
    'step.subscription.m-1.api.title': 'Configure Params / Self-hosted Cashier',
    'step.subscription.m-1.api.hint': 'Show collected binding parameters first, then enter the self-hosted cashier in the same step to select a payment method',
    'step.subscription.m-component.title': 'Get Token in Cashier',
    'step.subscription.m-component.hint': 'Load the component to get paymentToken and only complete frontend element collection',
    'step.subscription.m-order.title': 'First Binding Order',
    'step.subscription.m-order.hint': 'Frontend JS calls orderAndPay to complete first binding and displays the real request and response',
    'step.subscription.m-bind.title': 'First Payment Binding',
    'step.subscription.m-bind.hint': 'Cashier mode redirects to PayerMax and returns redirectUrl through orderAndPay',
    'step.subscription.m-bound.title': 'Complete Payment Binding',
    'step.subscription.m-bound.hint': 'Call orderQuery to query the first binding result and remind merchants to store paymentTokenID',
    'step.subscription.m-deduct.title': 'Subsequent Debit',
    'step.subscription.m-deduct.hint': 'Merchants initiate auto debits with paymentTokenID according to the subscription cycle',
    'step.subscription.np-1.title': 'Collect Business Data',
    'step.subscription.np-1.hint': 'Non-Periodic Auto Debit: merchants debit on demand; first binding sends UNSCHEDULED and generates a token',
    'step.subscription.np-1.api.title': 'Collect Data / Self-hosted Cashier',
    'step.subscription.np-1.api.hint': 'Show collected business data first, then enter the self-hosted cashier in the same step to select a payment method',
    'step.subscription.np-component.title': 'Get Token in Cashier',
    'step.subscription.np-component.hint': 'Load the component to get paymentToken and only complete frontend element collection',
    'step.subscription.np-order.title': 'First Binding Order',
    'step.subscription.np-order.hint': 'Frontend JS calls orderAndPay to complete first binding and displays the real request and response',
    'step.subscription.np-bind.title': 'First Payment Binding',
    'step.subscription.np-bind.hint': 'Cashier mode redirects to PayerMax and returns redirectUrl through orderAndPay',
    'step.subscription.np-bound.title': 'Complete Payment Binding',
    'step.subscription.np-bound.hint': 'Call orderQuery to query the first binding result and remind merchants to store paymentTokenID',
    'step.subscription.np-deduct.title': 'Subsequent Debit',
    'step.subscription.np-deduct.hint': 'Merchants initiate auto debits with paymentTokenID based on business needs',
  },
};

interface LanguageContextValue {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = React.createContext<LanguageContextValue | null>(null);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = React.useState<Language>(() => {
    if (typeof window === 'undefined') return 'zh-CN';
    return window.localStorage.getItem(STORAGE_KEY) === 'en-US' ? 'en-US' : 'zh-CN';
  });

  const setLanguage = React.useCallback((nextLanguage: Language) => {
    setLanguageState(nextLanguage);
    window.localStorage.setItem(STORAGE_KEY, nextLanguage);
  }, []);

  const t = React.useCallback((key: string) => {
    return dictionaries[language][key] ?? dictionaries['zh-CN'][key] ?? key;
  }, [language]);

  const value = React.useMemo(() => ({ language, setLanguage, t }), [language, setLanguage, t]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = React.useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
